import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()


def _env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_horizon_weights(name: str, default: str) -> dict[int, float]:
    """Parse comma-separated horizon weights such as ``5:0.4,10:0.3``."""
    raw = os.getenv(name, default)
    weights: dict[int, float] = {}
    for item in raw.split(","):
        item = item.strip()
        if not item:
            continue
        try:
            horizon_text, weight_text = item.split(":", 1)
            horizon = int(horizon_text.strip())
            weight = float(weight_text.strip())
        except (TypeError, ValueError):
            continue
        if horizon > 0 and weight >= 0:
            weights[horizon] = weight
    return weights


class Config:
    data_source: str = os.getenv("DATA_SOURCE", "yfinance")
    data_lookback_days: int = int(os.getenv("DATA_LOOKBACK_DAYS", "365"))
    kbs_base_url: str = os.getenv(
        "KBS_BASE_URL",
        "https://kbbuddywts.kbsec.com.vn/iis-server/investment",
    )
    kbs_timeout_seconds: float = float(os.getenv("KBS_TIMEOUT_SECONDS", "20"))
    paper_raw_data_dir: Path = Path(os.getenv("PAPER_RAW_DATA_DIR", "data/paper_raw"))
    paper_lookback_days: int = int(os.getenv("PAPER_LOOKBACK_DAYS", "1825"))
    paper_refresh_days: int = int(os.getenv("PAPER_REFRESH_DAYS", "120"))
    paper_strategy_name: str = os.getenv(
        "PAPER_STRATEGY_NAME",
        "vn30_rs_atr2_tp10",
    ).strip()
    paper_min_breadth_20d: float = float(
        os.getenv("PAPER_MIN_BREADTH_20D", "0.60")
    )
    paper_min_universe_count: int = int(
        os.getenv("PAPER_MIN_UNIVERSE_COUNT", "30")
    )
    paper_top_n: int = int(os.getenv("PAPER_TOP_N", "3"))
    paper_atr_multiple: float = float(os.getenv("PAPER_ATR_MULTIPLE", "2.0"))
    paper_take_profit: float = float(os.getenv("PAPER_TAKE_PROFIT", "0.10"))
    # Research and runtime use the same configurable baseline.  Keeping these
    # aliases explicit prevents the optimizer from silently drifting away
    # from the paper candidate's actual exit settings.
    ticker_exit_baseline_atr_multiple: float = float(
        os.getenv("TICKER_EXIT_BASELINE_ATR_MULTIPLE", os.getenv("PAPER_ATR_MULTIPLE", "2.0"))
    )
    ticker_exit_baseline_take_profit: float = float(
        os.getenv("TICKER_EXIT_BASELINE_TAKE_PROFIT", os.getenv("PAPER_TAKE_PROFIT", "0.10"))
    )
    ticker_exit_universe: str = os.getenv("TICKER_EXIT_UNIVERSE", "vn30").strip().lower()
    ticker_exit_walk_forward_folds: int = int(
        os.getenv("TICKER_EXIT_WALK_FORWARD_FOLDS", "3")
    )
    ticker_exit_minimum_consensus_folds: int = int(
        os.getenv("TICKER_EXIT_MINIMUM_CONSENSUS_FOLDS", "0")
    )
    ticker_exit_research_lookback_days: int = int(
        os.getenv("TICKER_EXIT_RESEARCH_LOOKBACK_DAYS", "1825")
    )
    ticker_exit_research_refresh_days: int = int(
        os.getenv("TICKER_EXIT_RESEARCH_REFRESH_DAYS", "120")
    )
    # Per-ticker exits are opt-in.  The profile file is generated by the
    # research CLI and the separate strategy name prevents mixing it with the
    # historical fixed-exit paper series.
    enable_ticker_exit_profiles: bool = _env_bool(
        "ENABLE_TICKER_EXIT_PROFILES", False
    )
    ticker_exit_profile_path: Path = Path(
        os.getenv(
            "TICKER_EXIT_PROFILE_PATH",
            "data/research_kbs_5y/research_results/ticker_exit_profiles.json",
        )
    )
    paper_ticker_exit_strategy_name: str = os.getenv(
        "PAPER_TICKER_EXIT_STRATEGY_NAME",
        "vn30_rs_ticker_exit_v1",
    ).strip()
    paper_min_trades: int = int(os.getenv("PAPER_MIN_TRADES", "100"))
    paper_target_trades: int = int(os.getenv("PAPER_TARGET_TRADES", "100"))
    paper_min_baskets: int = int(os.getenv("PAPER_MIN_BASKETS", "30"))
    paper_target_baskets: int = int(os.getenv("PAPER_TARGET_BASKETS", "50"))
    model_path: Path = Path(os.getenv("MODEL_PATH", "models/xgboost_model_h20.json"))
    dashboard_port: int = int(os.getenv("DASHBOARD_PORT", "8501"))
    log_level: str = os.getenv("LOG_LEVEL", "INFO")
    log_file: str = os.getenv("LOG_FILE", "logs/app.log")
    raw_data_dir: Path = Path("data/raw")
    processed_data_dir: Path = Path("data/processed")
    ssi_api_key: str | None = os.getenv("SSI_API_KEY")

    telegram_bot_token: str | None = os.getenv("TELEGRAM_BOT_TOKEN")
    telegram_chat_id: str | None = os.getenv("TELEGRAM_CHAT_ID")

    supabase_url: str | None = os.getenv("SUPABASE_URL")
    supabase_anon_key: str | None = os.getenv("SUPABASE_ANON_KEY")
    supabase_service_key: str | None = os.getenv("SUPABASE_SERVICE_KEY")

    stop_loss: float = float(os.getenv("STOP_LOSS", "-0.005"))
    take_profit: float = float(os.getenv("TAKE_PROFIT", "0.10"))
    # Conservative default for a complete buy/sell round trip. Override with
    # the broker-specific all-in cost when deploying.
    round_trip_cost: float = float(os.getenv("ROUND_TRIP_COST", "0.003"))
    # Use execution-aligned labels for T+20 when a fresh pipeline run builds
    # the feature file. Older files fall back to close-to-close columns.
    execution_target_enabled: bool = _env_bool("EXECUTION_TARGET_ENABLED", True)
    # Max-blend treats each horizon as a separate confirmation signal. The
    # weights remain useful when switching back to raw/rank blend modes.
    ensemble_horizon_weights: dict[int, float] = _env_horizon_weights(
        "ENSEMBLE_HORIZON_WEIGHTS", "1:1.0,5:1.0,10:1.0,20:1.0"
    )
    ensemble_blend_mode: str = os.getenv("ENSEMBLE_BLEND_MODE", "max").strip().lower()
    primary_ranking_strategy: str = os.getenv(
        "PRIMARY_RANKING_STRATEGY", "outperform"
    ).strip().lower()
    # Fail closed in weak market regimes; set this false only for a controlled
    # paper-test comparison.
    enable_entry_filters: bool = _env_bool("ENABLE_ENTRY_FILTERS", True)
    # Trend/breakout/fundamental modules remain available for research, but
    # their latest blocked OOS run does not justify letting them dilute the
    # production ensemble by default.
    enable_research_strategies: bool = _env_bool("ENABLE_RESEARCH_STRATEGIES", False)
    min_market_breadth_20d: float = float(os.getenv("MIN_MARKET_BREADTH_20D", "0.50"))
    min_entry_atr_percentile: float = float(os.getenv("MIN_ENTRY_ATR_PERCENTILE", "0.20"))
    min_entry_trend_percentile: float = float(os.getenv("MIN_ENTRY_TREND_PERCENTILE", "0.00"))
    min_entry_picks: int = int(os.getenv("MIN_ENTRY_PICKS", "3"))
    min_entry_score: float = float(os.getenv("MIN_ENTRY_SCORE", "0.10"))
    min_entry_score_margin: float = float(
        os.getenv("MIN_ENTRY_SCORE_MARGIN", "0.02")
    )
    # Keep the supervised model aligned with the current market regime.  A
    # bounded window also prevents stale 2025 observations from dominating a
    # 2026 signal when the cross-sectional regime has changed.
    model_training_days: int = int(os.getenv("MODEL_TRAINING_DAYS", "180"))
    model_quality_test_days: int = int(os.getenv("MODEL_QUALITY_TEST_DAYS", "40"))
    min_model_quality_dates: int = int(os.getenv("MIN_MODEL_QUALITY_DATES", "30"))
    min_model_roc_auc: float = float(os.getenv("MIN_MODEL_ROC_AUC", "0.52"))
    min_model_top3_excess_return: float = float(
        os.getenv("MIN_MODEL_TOP3_EXCESS_RETURN", "0.0")
    )
    min_model_top3_spread: float = float(
        os.getenv("MIN_MODEL_TOP3_SPREAD", "0.0")
    )

    def ensure_dirs(self) -> None:
        """Create directories using this config instance's paths."""
        Path(self.raw_data_dir).mkdir(parents=True, exist_ok=True)
        Path(self.processed_data_dir).mkdir(parents=True, exist_ok=True)
        Path(self.model_path).parent.mkdir(parents=True, exist_ok=True)
        Path(self.log_file).parent.mkdir(parents=True, exist_ok=True)

    def paper_strategy_names(self) -> set[str]:
        """Return all strategy names that use the isolated paper OHLC store."""
        return {
            self.paper_strategy_name,
            self.paper_ticker_exit_strategy_name,
        }

    def model_path_for_horizon(self, horizon: int) -> Path:
        """Return the persisted path for an ensemble horizon.

        ``MODEL_PATH`` is the primary production model used by inference and
        therefore owns the execution-aligned T+20 model.  Auxiliary horizon
        models keep their conventional paths so an override cannot silently
        be ignored for the model that inference actually loads.
        """
        if int(horizon) == 20:
            return Path(self.model_path)
        return Path("models") / f"xgboost_model_h{int(horizon)}.json"
